### ISSUE TITLE
net/http: HTTP/1.x transport connection broken: http: ContentLength=184 with Body length 238

### ISSUE THREAD

**Issue by skiloop** [crawlab-team/crawlab-core#6]
版本：0.6.0+
场景：浏览器上传文件
报告错误内容：
上传文件是失败，发生以下错误
```text
Post "http://localhost:8888/fs/63a43e1920ef271f2ed4e89a/c.txt": net/http: HTTP/1.x transport connection broken: http: ContentLength=184 with Body length 238
```

具体发生在向weedfs提交文件的时候。

抓包发现"github.com/imroc/req"会改变"boundary"
比如原始请求是
```text
POST / HTTP/1.1
Host: localhost:8011
User-Agent: curl/7.77.0
Accept: */*
Content-Length: 184
Content-Type: multipart/form-data; boundary=------------------------2f17f5c764d9af7f
Connection: keep-alive

--------------------------2f17f5c764d9af7f
Content-Disposition: form-data; name="file"; filename="c.txt"
Content-Type: text/plain

=
--------------------------2f17f5c764d9af7f--
```

req提交的内容是
```text
POST // HTTP/1.1
Host: localhost:8888
User-Agent: curl/7.77.0
Content-Length: 184
Accept: */*
Content-Type: multipart/form-data; boundary=c794b4a037e85e5128e14ad42dbd58bfe54f73b9eae044f020f3aca56b4e
Accept-Encoding: gzip
Connection: keep-alive

--c794b4a037e85e5128e14ad42dbd58bfe54f73b9eae044f020f3aca56b4e
Content-Disposition: form-data; name="file"; filename="c.txt"
Content-Type: application/octet-stream

=
--c794b4a037e85e5128e14ad42dbd58bfe54f73b9eae044f020f3aca56b4e
```

boundary由原来的"------------------------2f17f5c764d9af7"变成"c794b4a037e85e5128e14ad42dbd58bfe54f73b9eae044f020f3aca56b4e"，导致body内容长度发生改变，而头部Content-Length还保持原来的，因而不匹配，上传失败。

不确定整个0.6.0+都有问题，我有台机子是没有错误的，有待检查。

**Comment by tikazyq** [comment]
是否可以发一下上传的文件

另外是否每个文件上传都有问题？

**Comment by skiloop** [comment]
> 是否可以发一下上传的文件
> 
> 另外是否每个文件上传都有问题？

每个文件都有问题

**Comment by tikazyq** [comment]
可以发一下docker的配置信息么，去掉敏感信息

**Comment by skiloop** [comment]
好像的确是docker或者go版本的问题，我镜像都更新到最新，正常机子还是正常的，异常还是异常的。
这是异常机子的docker版本信息
```text
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.2
 Git commit:        20.10.12-0ubuntu2~20.04.1
 Built:             Wed Apr  6 02:14:38 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.2
  Git commit:       20.10.12-0ubuntu2~20.04.1
  Built:            Thu Feb 10 15:03:35 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.9-0ubuntu1~20.04.6
  GitCommit:        
 runc:
  Version:          1.1.0-0ubuntu1~20.04.2
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        

```

正常机子的docker版本信息是：

```text
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:04:24 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:02:38 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

问题的关键在于正常机子，提交到filer接口的请求没带Content-Length，而异常的带了。但是filer接口处理方式是直接复制头，因此也把原来的长度带过去了。

**Comment by skiloop** [comment]
> 可以发一下docker的配置信息么，去掉敏感信息

docker-compose.yml吗?

**Comment by tikazyq** [comment]
> > 可以发一下docker的配置信息么，去掉敏感信息
> 
> docker-compose.yml吗?

是的，我说的是这个😂

**Comment by skiloop** [comment]
> 

```yml
version: '3.3'
services:
  mongo:
    image: mongo:4.2
    container_name: mongo
    restart: always
    networks:
      - crawlab
  master:
    image: crawlabteam/crawlab:latest
    container_name: master
    hostname: master
    networks:
      - crawlab
    env_file:
      - ./master-env.sh
    ports:
      - "8081:8080" # frontend port mapping 前端端口映射
      - "8000:8000" # frontend port mapping 前端端口映射
      - "9666:9666" # rpc ports
    depends_on:
      - mongo
    volumes:
    - "./log/master:/var/log/crawlab" # log persistent 日志持久化
    - "crawlab-master:/data" # log persistent 日志持久化


networks:
  crawlab:
     driver: bridge
volumes:
  crawlab-master: {}

```
